CREATE DATABASE sd4;

CREATE TABLE students(
 student_id INT PRIMARY KEY AUTO_INCREMENT,
 first_name VARCHAR(15),
 last_name VARCHAR(30),
 email VARCHAR(255) DEFAULT 'Não infromado',
 embaixa_tryber INT(1) DEFAULT 0
 );
 
INSERT INTO students
VALUES 
('Alexandre', 'Oliveira Anício Costa'),
('Alice','Arruda Atalla'),
('Caio', 'Bueno Ribeiro', 'cacobribeiro@gmail.com'),
('Caio','Luiz Magalhães Fernandes'),
('Cezene','Silva Neves'),
('Daniel','Cordeiro Pantalena'),
('Daniel','de Lacerda Miranda'),
('Danilo', 'dos Santos Souza', 'danilosantossousa@gmail.com'),
('Diego','Matheus Campos'),
('Djonata', 'de Souza Dias', 'danilosantossousa@gmail.com'),
('Douglas','Costa'),
('Douglas','Henrique da Silva'),
('Débora','Cardoso de Oliveira Silveira'),
('Eder','Sena'),
('Eduardo','dos Santos Flores'),
('Fabiola',' Figueira deiró dos Santos'),
('Fanderson','Kaecio'),
('Felipe Caetano',''),
('Filipe','de Castro Oliveira'),
('Frederico','Mendonça Campelli'),
('Gabriel','Almeida'),
('Henrique','Baeta Leite'),
('Hugo','Joaquim de Moro Junior'),
('Igor','Giamoniano Pereira'),
('Ilan','Herbach');
('Jorge','Henrique Shiniti Osiro'),
('Josias','Danny de Viveiro'),
('João','Souto'),
('Juliana','de Fatima da Silva'),
('Julio','Cesar Tinin'),
('Julio','Melo'),
('Jéssica','Tavares', 'Não infromado',1),
('Leandro','Kaoru'),
('Leandro','Marten'),
('Leonardo','Costa Damasceno'),
('Leonardo','Xavier'),
('Lourenço','Lage'),
('Lucas','Barbosa Rosa'),
('Lucas','Lima Yoshida'),
('Lucas','Okazava Machado'),
('Lucas','Procopio'),
('Lucas','Ribas'),
('Matheus','Yuri Silva Domingos', 'Não informado', 1),
('Mathieu','Bouhelier'),
('Orlando','Messias'),
('Pedro', 'Pires', 'pedrotpoliveira@gmail.com'),
('Rafael','Passos Barbosa'),
('Rangel', 'Paolo Cardoso Bomfim', 'gelcardoso2012@gmail.com'),
('Rangel','Paolo Cardoso Bonfim'),
('Robson',' Will Corrêia da Silva'),
('Ronald','de Azevedo Lima'),
('Ronan','Fernandes Correia'),
('Tereza', 'Cristina Simões Carvalho', 'terezasimoes@gmail.com'),
('Thabata','Dornelas'),
('Thiago','Tavares'),
('Tiago','Tiago Emanuel Reis Silva'),

 
 